# Pandas (Series)

In [1]:
# Why Pandas? 

# Pandas is a powerful and flexible open-source data analysis and manipulation library for Python. 

# It provides data structures like DataFrames and Series that make it easy to work with structured data. 

# Here are some reasons why Pandas is widely used:  
# 01. Easy to use.
# 02. Efficient: Pandas is built on top of NumPy - fast and efficient data processing, even with large datasets.
# 03. Versatile: Pandas can handle a wide variety of data formats, including CSV, Excel, SQL databases, etc.
# 04. Integration: Pandas integrates well with other Python libraries, such as Matplotlib, Scikit-learn.
# 05. Community support
# 06. Data Cleaning: 
#      - Pandas provides robust tools for cleaning and preparing data, including:
#           1. handling missing values
#           2. handling duplicates
#           3. handling inconsistent data types

# 07. Data Transformation: Pandas allows for easy reshaping and pivoting of data
# 08. Performance: Pandas is optimized for performance, allowing for efficient data manipulation and analysis
# 09. Visualization: Pandas has built-in support for basic data visualization
# 10. Documentation: Pandas has comprehensive documentation and tutorials
# 11. Pandas is open-source software
# 12. Data Alignment: Pandas automatically aligns data for you when performing operations on different datasets
# 13. Time Series Analysis: Pandas provides specialized functionality for working with time series data
# 14. Grouping and Aggregation: Pandas makes it easy to group data by one or more keys and perform aggregate functions
# 15. Extensibility: Pandas can be extended with custom functions and methods

In [2]:
# always import pandas and numpy at the beginning of your script

import numpy as np
import pandas as pd

In [3]:
# What is Series? 

# A Series is a 1D labeled array capable of holding any data type (integers, strings, float, Python objects, etc.).
# The labels, also known as the index, allow for easy access and manipulation of data.  

# We can create a Series from a list, NumPy array, or dictionary.

In [4]:
# Series of strings

countries = ['Pakistan', 'India', 'Bangladesh','Afghanistan', 'Nepal', 'Sri Lanka', 'Bhutan', 'Maldives']   

pd.Series(countries)

# Series is a class inside Pandas library. 
# We can create a Series object by calling the Series class and passing in the data we want to store in the Series.

0       Pakistan
1          India
2     Bangladesh
3    Afghanistan
4          Nepal
5      Sri Lanka
6         Bhutan
7       Maldives
dtype: str

In [5]:
# Series of integers

runs_Kohli = [183, 160, 122, 97, 82, 70, 65, 55]

pd.Series(runs_Kohli)

0    183
1    160
2    122
3     97
4     82
5     70
6     65
7     55
dtype: int64

In [6]:
# Custom index instead of 0,1,2,3,4,5,6,7

marks_Arsalan = [85, 90, 78, 92, 88]
subjects = ['Math', 'Science', 'English', 'History', 'Geography']

pd.Series(marks_Arsalan, index=subjects)

Math         85
Science      90
English      78
History      92
Geography    88
dtype: int64

In [7]:
marks_series = pd.Series(marks_Arsalan, index=subjects, name='Arsalan ke Marks')

marks_series
# the name is like a title or ID for the Series. 
# It can be useful when working with multiple Series or when displaying the data in a DataFrame.

Math         85
Science      90
English      78
History      92
Geography    88
Name: Arsalan ke Marks, dtype: int64

In [8]:
# Series from dictionary

marks_dict = {
    'Math': 85,
    'Science' : 90,
    'English' : 78,
    'History' : 92,
    'Geography' : 88
}

marks_dict

{'Math': 85, 'Science': 90, 'English': 78, 'History': 92, 'Geography': 88}

# Series Attributes

In [9]:


# size of a series

marks_series.size

5

In [10]:
# data type of a series

marks_series.dtype

dtype('int64')

In [11]:
# name of a series

marks_series.name

'Arsalan ke Marks'

In [12]:
# is_unique

# this will show if all the values in the series are unique or not. 
# It will return True if all values are unique, otherwise it will return False.

marks_series.is_unique

True

In [13]:
# I just want to check whether the is_unique attribute is working or not. 
# So, I will create a new list with some duplicate values and then create a new Series from that list.

marks_new = [20, 15 ,20, 50, 95, 80]
subjects_new = ['Math', 'Science', 'English', 'History', 'Geography', 'Math']

marks_series_new = pd.Series(marks_new, index = subjects_new, name='Marks with Duplicates')
marks_series_new

Math         20
Science      15
English      20
History      50
Geography    95
Math         80
Name: Marks with Duplicates, dtype: int64

In [14]:
marks_series_new.is_unique

False

In [15]:
# index items

marks_series.index

Index(['Math', 'Science', 'English', 'History', 'Geography'], dtype='str')

In [16]:
# values (instead of index)

marks_series.values

array([85, 90, 78, 92, 88])

# Series using read_csv 

(i.e. reading an existing data set)

In [17]:
# csv files mean Comma Separated Values files.
# In such files, data is stored in a tabular format.
# each row represents a record and each column represents a field (attribute).

# I have already downloaded the three csv files which the teacher have used in the video. You can download them from the following links:
# https://raw.githubusercontent.com/arsal3646/Python_Projects/main/CampusX_Data_Science_Course/016_DataSets_Pandas/subs.csv

subs = pd.read_csv('https://raw.githubusercontent.com/arsal3646/Python_Projects/main/CampusX_Data_Science_Course/016_DataSets_Pandas/subs.csv')

subs

     Subscribers gained
0                    48
1                    57
2                    40
3                    43
4                    44
..                  ...
360                 231
361                 226
362                 155
363                 144
364                 172

[365 rows x 1 columns]

In [18]:
# Note: the type of the above object is automatically a DataFrame, not a Series.

type(subs)

pandas.DataFrame

In [19]:
# we need to convert the DataFrame into a Series.
# this is done by using Squeeze method, i.e. squeeze = True

subs_series = subs.squeeze() 

# you can also doing the same directly while reading the csv file by using the squeeze parameter.
# the code would have been like this:
# subs_series = pd.read_csv('https://raw.githubusercontent.com/arsal3646/Python_Projects/main/CampusX_Data_Science_Course/016_DataSets_Pandas/subs.csv', squeeze=True)

subs_series

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [ ]:
subs_series.name

# the name of the Series is automatically set to the name of the column in the DataFrame.

'Subscribers gained'

In [ ]:
type(subs_series)

# now it is changed to a Series object from a DataFrame object.

pandas.Series

In [ ]:
# Pandas Series - with one column

subs_series

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [44]:
import pandas as pd

urls = [
    "https://raw.githubusercontent.com/arsal3646/Python_Projects/main/CampusX_Data_Science_Course/016_DataSets_Pandas/kohli_ipl.csv",
    "https://raw.githubusercontent.com/arsal3646/Python_Projects/master/CampusX_Data_Science_Course/016_DataSets_Pandas/kohli_ipl.csv",
    "https://raw.githubusercontent.com/arsal3646/Python_Projects/main/CampusX_Data_Science_Course/016_DataSets_Pandas/kohli_runs.csv",
    "https://raw.githubusercontent.com/arsal3646/Python_Projects/master/CampusX_Data_Science_Course/016_DataSets_Pandas/kohli_runs.csv",
]

for url in urls:
    try:
        kohli = pd.read_csv(url, index_col="match_no").squeeze("columns")
        print("Loaded from:", url)
        break
    except Exception as e:
        print("Failed:", url)

kohli

Loaded from: https://raw.githubusercontent.com/arsal3646/Python_Projects/main/CampusX_Data_Science_Course/016_DataSets_Pandas/kohli_ipl.csv

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64

In [45]:
# now let us use kohli_runs.csv file to create a Series with 2 columns.

import pandas as pd

kohli = pd.read_csv(
    'https://raw.githubusercontent.com/arsal3646/Python_Projects/main/CampusX_Data_Science_Course/016_DataSets_Pandas/kohli_ipl.csv',
    index_col='match_no'
).squeeze('columns')

kohli

match_no
1       1
2      23
3      13
4      12
5       1
       ..
211     0
212    20
213    73
214    25
215     7
Name: runs, Length: 215, dtype: int64

In [46]:
bollywood = pd.read_csv(
    'https://raw.githubusercontent.com/arsal3646/Python_Projects/main/CampusX_Data_Science_Course/016_DataSets_Pandas/bollywood.csv'
)

bollywood

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

In [49]:
# Pandas Series -  with 2 columns  
 
bollywood_series = bollywood.squeeze('columns')

bollywood_series

                                     movie              lead
0                 Uri: The Surgical Strike     Vicky Kaushal
1                            Battalion 609       Vicky Ahuja
2     The Accidental Prime Minister (film)       Anupam Kher
3                          Why Cheat India     Emraan Hashmi
4                          Evening Shadows  Mona Ambegaonkar
...                                    ...               ...
1495                Hum Tumhare Hain Sanam    Shah Rukh Khan
1496                   Aankhen (2002 film)  Amitabh Bachchan
1497                       Saathiya (film)      Vivek Oberoi
1498                        Company (film)        Ajay Devgn
1499                  Awara Paagal Deewana      Akshay Kumar

[1500 rows x 2 columns]

# Series Methods

In [54]:
# head and tail methods

bollywood_series.head(3)  # this will show the first 3 rows of the Series

                                  movie           lead
0              Uri: The Surgical Strike  Vicky Kaushal
1                         Battalion 609    Vicky Ahuja
2  The Accidental Prime Minister (film)    Anupam Kher

In [55]:
kohli.head(3)  # this will show the first 3 rows of the Series

match_no
1     1
2    23
3    13
Name: runs, dtype: int64

In [56]:
kohli.tail(10)  # this will show the last 10 rows of the Series

match_no
206     0
207     0
208     9
209    58
210    30
211     0
212    20
213    73
214    25
215     7
Name: runs, dtype: int64

In [58]:
bollywood_series.tail(8)  # this will show the last 8 rows of the Series

                           movie              lead
1492  Waisa Bhi Hota Hai Part II      Arshad Warsi
1493    Devdas (2002 Hindi film)    Shah Rukh Khan
1494                      Kaante  Amitabh Bachchan
1495      Hum Tumhare Hain Sanam    Shah Rukh Khan
1496         Aankhen (2002 film)  Amitabh Bachchan
1497             Saathiya (film)      Vivek Oberoi
1498              Company (film)        Ajay Devgn
1499        Awara Paagal Deewana      Akshay Kumar

In [59]:
# sample method shows a random sample of rows from the Series.

kohli.sample()

match_no
140    5
Name: runs, dtype: int64

In [69]:
bollywood_series.sample(10)  # this will show a random sample of 10 rows from the Series

                              movie              lead
1060  The Blue Umbrella (2005 film)      Pankaj Kapur
293                  Sarbjit (film)     Randeep Hooda
832               Teen Patti (film)  Amitabh Bachchan
460                   Jai Ho (film)       Salman Khan
656                         Lootera     Ranveer Singh
190          Half Girlfriend (film)   Shraddha Kapoor
409               Welcome 2 Karachi      Arshad Warsi
612                      Policegiri       Sanjay Dutt
1499           Awara Paagal Deewana      Akshay Kumar
292              Phobia (2016 film)      Radhika Apte

Studied until min 52