In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

courses = pd.read_csv('/Users/arsalanafridi/Documents/GitHub/Python_Projects/Python_Projects/CampusX_Data_Science_Course/020_DataSets_Merging/courses.csv')
students = pd.read_csv('/Users/arsalanafridi/Documents/GitHub/Python_Projects/Python_Projects/CampusX_Data_Science_Course/020_DataSets_Merging/students.csv')
nov = pd.read_csv('/Users/arsalanafridi/Documents/GitHub/Python_Projects/Python_Projects/CampusX_Data_Science_Course/020_DataSets_Merging/reg-month1.csv')
dec = pd.read_csv('/Users/arsalanafridi/Documents/GitHub/Python_Projects/Python_Projects/CampusX_Data_Science_Course/020_DataSets_Merging/reg-month2.csv')
matches = pd.read_csv('/Users/arsalanafridi/Documents/GitHub/Python_Projects/Python_Projects/CampusX_Data_Science_Course/020_DataSets_Merging/matches.csv')
delivery = pd.read_csv('/Users/arsalanafridi/Documents/GitHub/Python_Projects/Python_Projects/CampusX_Data_Science_Course/020_DataSets_Merging/deliveries.csv')

In [4]:
courses

    course_id       course_name  price
0           1            python   2499
1           2               sql   3499
2           3     data analysis   4999
3           4  machine learning   9999
4           5           tableau   2499
5           6          power bi   1899
6           7          ms sxcel   1599
7           8            pandas   1099
8           9            plotly    699
9          10           pyspark   2499
10         11             Numpy    699
11         12               C++   1299

In [3]:
students

    student_id                name  partner
0            1       Kailash Harjo       23
1            2         Esha Butala        1
2            3      Parveen Bhalla        3
3            4         Marlo Dugal       14
4            5         Kusum Bahri        6
5            6  Lakshmi Contractor       10
6            7        Tarun Thaker        9
7            8      Radheshyam Dey        5
8            9   Nitika Chatterjee        4
9           10      Aayushman Sant        8
10          11  David Mukhopadhyay       20
11          12          Radha Dutt       19
12          13      Munni Varghese       24
13          14    Pranab Natarajan       22
14          15           Preet Sha       16
15          16        Elias Dodiya       25
16          17        Yasmin Palan        7
17          18     Fardeen Mahabir       13
18          19        Qabeel Raman       12
19          20       Hanuman Hegde       11
20          21          Seema Kota       15
21          22          Yash Sethi       21
22          23      Chhavi Lachman       18
23          24        Radhika Suri       17
24          25     Shashank D’Alia        2

In [5]:
matches

,id,season,city,date,team1,team2,toss_winner,toss_decision,result,dl_applied,winner,win_by_runs,win_by_wickets,player_of_match,venue,umpire1,umpire2,umpire3
0,1,2017,Hyderabad,2017-04-05,Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Sunrisers Hyderabad,35,0,Yuvraj Singh,"Rajiv Gandhi International Stadium, Uppal",AY Dandekar,NJ Llong,NaN
1,2,2017,Pune,2017-04-06,Mumbai Indians,Rising Pune Supergiant,Rising Pune Supergiant,field,normal,0,Rising Pune Supergiant,0,7,SPD Smith,Maharashtra Cricket Association Stadium,A Nand Kishore,S Ravi,NaN
2,3,2017,Rajkot,2017-04-07,Gujarat Lions,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Kolkata Knight Riders,0,10,CA Lynn,Saurashtra Cricket Association Stadium,Nitin Menon,CK Nandan,NaN
3,4,2017,Indore,2017-04-08,Rising Pune Supergiant,Kings XI Punjab,Kings XI Punjab,field,normal,0,Kings XI Punjab,0,6,GJ Maxwell,Holkar Cricket Stadium,AK Chaudhary,C Shamshuddin,NaN
4,5,2017,Bangalore,2017-04-08,Royal Challengers Bangalore,Delhi Daredevils,Royal Challengers Bangalore,bat,normal,0,Royal Challengers Bangalore,15,0,KM Jadhav,M Chinnaswamy Stadium,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
631,632,2016,Raipur,2016-05-22,Delhi Daredevils,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,6,V Kohli,Shaheed Veer Narayan Singh International Stadium,A Nand Kishore,BNJ Oxenford,NaN
632,633,2016,Bangalore,2016-05-24,Gujarat Lions,Royal Challengers Bangalore,Royal Challengers Bangalore,field,normal,0,Royal Challengers Bangalore,0,4,AB de Villiers,M Chinnaswamy Stadium,AK Chaudhary,HDPK Dharmasena,NaN
633,634,2016,Delhi,2016-05-25,Sunrisers Hyderabad,Kolkata Knight Riders,Kolkata Knight Riders,field,normal,0,Sunrisers Hyderabad,22,0,MC Henriques,Feroz Shah Kotla,M Erasmus,C Shamshuddin,NaN
634,635,2016,Delhi,2016-05-27,Gujarat Lions,Sunrisers Hyderabad,Sunrisers Hyderabad,field,normal,0,Sunrisers Hyderabad,0,4,DA Warner,Feroz Shah Kotla,M Erasmus,CK Nandan,NaN
635,636,2016,Bangalore,2016-05-29,Sunrisers Hyderabad,Royal Challengers Bangalore,Sunrisers Hyderabad,bat,normal,0,Sunrisers Hyderabad,8,0,BCJ Cutting,M Chinnaswamy Stadium,HDPK Dharmasena,BNJ Oxenford,NaN

In [6]:
nov

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9           15          1
10          19          4
11           1          6
12           7         10
13          11          7
14          13          3
15          24          4
16          21          1
17          16          5
18          23          3
19          17          7
20          23          6
21          25          1
22          19          2
23          25         10
24           3          3

In [7]:
dec

    student_id  course_id
0            3          5
1           16          7
2           12         10
3           12          1
4           14          9
5            7          7
6            7          2
7           16          3
8           17         10
9           11          8
10          14          6
11          12          5
12          12          7
13          18          8
14           1         10
15           1          9
16           2          5
17           7          6
18          22          5
19          22          6
20          23          9
21          23          5
22          14          4
23          14          1
24          11         10
25          42          9
26          50          8
27          38          1

In [ ]:
nov.shape

# this means 25 students registered in November and 28 students registered in December.

(25, 2)

In [10]:
dec.shape

(28, 2)

In [8]:
delivery

,match_id,inning,batting_team,bowling_team,over,ball,batsman,non_striker,bowler,is_super_over,...,bye_runs,legbye_runs,noball_runs,penalty_runs,batsman_runs,extra_runs,total_runs,player_dismissed,dismissal_kind,fielder
0,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,1,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
1,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,2,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
2,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,3,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN
3,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,4,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,0,0,NaN,NaN,NaN
4,1,1,Sunrisers Hyderabad,Royal Challengers Bangalore,1,5,DA Warner,S Dhawan,TS Mills,0,...,0,0,0,0,0,2,2,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
150455,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,2,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,2,0,2,NaN,NaN,NaN
150456,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,3,Sachin Baby,CJ Jordan,B Kumar,0,...,0,0,0,0,0,0,0,CJ Jordan,run out,NV Ojha
150457,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,4,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,1,0,0,0,1,1,NaN,NaN,NaN
150458,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,5,Sachin Baby,Iqbal Abdulla,B Kumar,0,...,0,0,0,0,1,0,1,NaN,NaN,NaN
150459,636,2,Royal Challengers Bangalore,Sunrisers Hyderabad,20,6,Iqbal Abdulla,Sachin Baby,B Kumar,0,...,0,0,0,0,4,0,4,NaN,NaN,NaN

In [ ]:
# pd.concat

# this is used to combine two dataframes. It can be used to combine dataframes vertically or horizontally.

# for example we can concatenate the two dataframes nov and dec vertically to get a single dataframe with all the students 
# who registered in November and December.

all_students = pd.concat([nov, dec])

all_students.shape

# this will 25 +28 = 53 students in total.

(53, 2)

In [ ]:
all_students.head(30)

# You will notice here that after row 23 (end of nov dataframe), the index starts from 0 again. 
# This is because the index is not reset after concatenation. 
# We can reset the index using the reset_index() method.

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9           15          1
10          19          4
11           1          6
12           7         10
13          11          7
14          13          3
15          24          4
16          21          1
17          16          5
18          23          3
19          17          7
20          23          6
21          25          1
22          19          2
23          25         10
24           3          3
0            3          5
1           16          7
2           12         10
3           12          1
4           14          9

In [19]:
# we can reset the index of the all_students dataframe using the reset_index() method. 
# We can also drop the old index using the drop=True parameter.
all_students = all_students.reset_index(drop=True)
all_students

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9           15          1
10          19          4
11           1          6
12           7         10
13          11          7
14          13          3
15          24          4
16          21          1
17          16          5
18          23          3
19          17          7
20          23          6
21          25          1
22          19          2
23          25         10
24           3          3
25           3          5
26          16          7
27          12         10
28          12          1
29          14          9
30           7          7
31           7          2
32          16          3
33          17         10
34          11          8
35          14          6
36          12          5
37          12          7
38          18          8
39           1         10
40           1          9
41           2          5
42           7          6
43          22          5
44          22          6
45          23          9
46          23          5
47          14          4
48          14          1
49          11         10
50          42          9
51          50          8
52          38          1

In [20]:
# also we can use ignore_index=True parameter in the concat() method to reset the index after concatenation.
all_students = pd.concat([nov, dec], ignore_index=True)
all_students

    student_id  course_id
0           23          1
1           15          5
2           18          6
3           23          4
4           16          9
5           18          1
6            1          1
7            7          8
8           22          3
9           15          1
10          19          4
11           1          6
12           7         10
13          11          7
14          13          3
15          24          4
16          21          1
17          16          5
18          23          3
19          17          7
20          23          6
21          25          1
22          19          2
23          25         10
24           3          3
25           3          5
26          16          7
27          12         10
28          12          1
29          14          9
30           7          7
31           7          2
32          16          3
33          17         10
34          11          8
35          14          6
36          12          5
37          12          7
38          18          8
39           1         10
40           1          9
41           2          5
42           7          6
43          22          5
44          22          6
45          23          9
46          23          5
47          14          4
48          14          1
49          11         10
50          42          9
51          50          8
52          38          1

In [22]:
# another way is to use the append() method. 
# This method is used to append rows of one dataframe to another dataframe.

# but this method is deprecated and will be removed in a future version.

In [27]:
multi = pd.concat([nov, dec], keys=['nov', 'dec'])

# This will create a multi-index dataframe with the keys 'nov' and 'dec' as the first level of the index.

In [28]:
# loc is for index based selection and iloc is for position based selection.

multi.loc['dec']

    student_id  course_id
0            3          5
1           16          7
2           12         10
3           12          1
4           14          9
5            7          7
6            7          2
7           16          3
8           17         10
9           11          8
10          14          6
11          12          5
12          12          7
13          18          8
14           1         10
15           1          9
16           2          5
17           7          6
18          22          5
19          22          6
20          23          9
21          23          5
22          14          4
23          14          1
24          11         10
25          42          9
26          50          8
27          38          1

In [29]:
# what if we want to select the first 5 rows of the dec dataframe from the multi-index dataframe?

multi.loc['dec'].iloc[:5]

   student_id  course_id
0           3          5
1          16          7
2          12         10
3          12          1
4          14          9

In [ ]:
multi.loc['nov'].iloc[0]    # this will give the first row of the nov dataframe from the multi-index dataframe.

In [30]:
# we can stack horizontally as well. 
# For example, we can concatenate the two dataframes nov and dec horizontally to get a single dataframe with all the students 
# who registered in November and December.

pd.concat([nov, dec], axis=1)

    student_id  course_id  student_id  course_id
0         23.0        1.0           3          5
1         15.0        5.0          16          7
2         18.0        6.0          12         10
3         23.0        4.0          12          1
4         16.0        9.0          14          9
5         18.0        1.0           7          7
6          1.0        1.0           7          2
7          7.0        8.0          16          3
8         22.0        3.0          17         10
9         15.0        1.0          11          8
10        19.0        4.0          14          6
11         1.0        6.0          12          5
12         7.0       10.0          12          7
13        11.0        7.0          18          8
14        13.0        3.0           1         10
15        24.0        4.0           1          9
16        21.0        1.0           2          5
17        16.0        5.0           7          6
18        23.0        3.0          22          5
19        17.0        7.0          22          6
20        23.0        6.0          23          9
21        25.0        1.0          23          5
22        19.0        2.0          14          4
23        25.0       10.0          14          1
24         3.0        3.0          11         10
25         NaN        NaN          42          9
26         NaN        NaN          50          8
27         NaN        NaN          38          1

In [ ]:
pd.concat([nov, dec], axis=1).shape

# note the NaN values in the last 3 rows of the nov dataframe. 
# This is because the nov dataframe has 25 rows and the dec dataframe has 28 rows.
# It was automatically filled with NaN values to match the number of rows in the dec dataframe. 
# Who did this automatically? Pandas did this automatically.

(28, 4)

# watched the video until min 29